blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/Moonfin-Client/Tizen/discussions
    about: Please ask usage questions here instead of opening an issue.
